%% Main Analysis Script for Model Training and SHAP Analysis
% This script runs the pyrolysis model training and then performs SHAP analysis
% on the trained model to explain feature importance and prediction explanations

% Clear workspace and command window
clc; clear all; close all;

% Set warning preferences - disable warnings for numerical precision in nchoosek
warning('off', 'MATLAB:nchoosek:LargeCoefficient');
% Turn off potential parallel pool warnings
warning('off', 'parallel:pctexample:parallelize');
% Turn off path warnings for removing non-existent paths
warning('off', 'MATLAB:rmpath:DirNotFound');
% Turn off mkdir warnings for creating existing directories
warning('off', 'MATLAB:MKDIR:DirectoryExists');
% Turn off strsplit deprecated warning
warning('off', 'MATLAB:string:functionsToBeRemoved');

% Check MATLAB version for compatibility adjustments
matlabVersion = version;
isOlderMatlab = verLessThan('matlab', '9.1'); % R2016b or earlier
if isOlderMatlab
    disp(['Note: Running on MATLAB version ' matlabVersion ' - adjusting for compatibility']);
else
    disp(['MATLAB version: ' matlabVersion]);
end

% Set up paths - Fix path settings
% First get the current script directory
scriptPath = mfilename('fullpath');
[scriptDir, ~, ~] = fileparts(scriptPath);
% Get project root directory (up one level)
rootDir = fileparts(fileparts(scriptDir));
% Set model files and results directories correctly
modelFilesDir = fullfile(rootDir, 'bpDNN4PyroProd_modelfiles');
resultsDir = fullfile(rootDir, 'GPM_SHAP_matlab', 'Results');

% Set up subdirectories for better organization
trainingDir = fullfile(resultsDir, 'Training_Debug');
shapDir = fullfile(resultsDir, 'SHAP_Analysis_Debug');

% Improved path handling - check if path exists before removing to avoid warnings
try
    % Use textscan instead of strsplit for compatibility
    pathList = textscan(path, '%s', 'Delimiter', pathsep);
    pathList = pathList{1};
    
    % Check if rootDir is in the path
    if any(contains(pathList, rootDir))
        rmpath(genpath(rootDir));
        disp('Removed existing paths to avoid conflicts');
    end
catch ME
    disp(['Path handling error: ' ME.message]);
end

% Then add the model files directory to the MATLAB path
addpath(genpath(modelFilesDir));
addpath(genpath(scriptDir)); % Add scripts directory to path

% Check if required functions exist
requiredFunctions = {'nncreate', 'nnpredict', 'nnpreprocess', 'nntrain', 'nneval'};
missingFunctions = {};
for i = 1:length(requiredFunctions)
    if ~exist(requiredFunctions{i}, 'file')
        missingFunctions{end+1} = requiredFunctions{i};
    end
end

if ~isempty(missingFunctions)
    error('Missing required functions: %s. Please ensure these files are in bpDNN4PyroProd_modelfiles and the directory is in the MATLAB path.', strjoin(missingFunctions, ', '));
end

% Create results directories if they don't exist
if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end
if ~exist(trainingDir, 'dir')
    mkdir(trainingDir);
end
if ~exist(shapDir, 'dir')
    mkdir(shapDir);
end

%% Step 1: Run the model training script with modified epoch number
disp('Starting model training with reduced epochs (60) for faster debugging...');
disp(['Model files directory: ' modelFilesDir]);
disp(['Results will be saved in: ' trainingDir]);

% Save current directory
originalDir = pwd;

% Switch to model files directory
cd(modelFilesDir);

% Create a temporary copy of the model training script with reduced epochs
originalScript = fullfile(modelFilesDir, 'bpDNN4PyroProd.m');
originalScript = strrep(originalScript, '\', '/'); % Use forward slashes for consistency
tempScript = fullfile(modelFilesDir, 'bpDNN4PyroProd_temp.m');
tempScript = strrep(tempScript, '\', '/'); % Use forward slashes for consistency

% Check if original script exists
if ~exist(originalScript, 'file')
    error('Original script not found: %s', originalScript);
end

try
    % Read the original script
    fid = fopen(originalScript, 'r');
    if fid == -1
        error('Could not open file: %s', originalScript);
    end
    scriptContent = fread(fid, '*char')';
    fclose(fid);
    
    % Replace the epoch number (6000) with 60
    modifiedContent = strrep(scriptContent, 'net.trainParam.epoch = 6000;', 'net.trainParam.epoch = 60;');
    
    % Comment out both "clear all" commands to prevent variable clearing
    modifiedContent = strrep(modifiedContent, 'clc;clear all', 'clc;% clear all  % Commented out to preserve variables');
    modifiedContent = strrep(modifiedContent, 'clear all', '% clear all  % Commented out to preserve variables');
    
    % Add code to store global variables in the workspace
    modifiedContent = strrep(modifiedContent, 'global PS TS;', ...
        ['global PS TS;' newline ...
         'fprintf(''Ensuring global preprocessing variables are captured\n'');' newline ...
         'evalin(''base'', ''global PS TS;'');' newline ... % Ensure globals are visible in base workspace
         'if exist(''PS'', ''var'') && ~isempty(PS)' newline ... % Check if PS exists and is not empty
         '    PS_global = PS;' newline ...
         '    assignin(''base'', ''PS_global'', PS);' newline ... 
         'end' newline ...
         'if exist(''TS'', ''var'') && ~isempty(TS)' newline ... % Check if TS exists and is not empty
         '    TS_global = TS;' newline ...
         '    assignin(''base'', ''TS_global'', TS);' newline ...
         'end']);
    
    % Replace the save locations to use our training directory with proper path handling
    figDirPath = fullfile(trainingDir, 'Figures');
    figDirPath = strrep(figDirPath, '\', '/'); % Use forward slashes for consistency
    
    modifiedContent = strrep(modifiedContent, 'mkdir(''Figures'');', ...
        ['if ~exist(''' figDirPath ''', ''dir'')' newline ...
         '    mkdir(''' figDirPath ''');' newline ...
         'end']);
    
    modifiedContent = strrep(modifiedContent, 'FolderName = ''Figures'';', ['FolderName = ''' figDirPath ''';']);
    
    % Modified save command to explicitly ensure PS_global and TS_global are saved
    saveFilePath = fullfile(trainingDir, 'Results_trained.mat');
    saveFilePath = strrep(saveFilePath, '\', '/'); % Use forward slashes for consistency
    
    saveCmd = ['% Create PS_global and TS_global if they don''t exist' newline ...
               'global PS TS;' newline ...
               'if ~exist(''PS_global'', ''var'') && exist(''PS'', ''var'') && ~isempty(PS)' newline ...
               '    PS_global = PS;' newline ...
               '    fprintf(''Created PS_global from PS\n'');' newline ...
               'end' newline ...
               'if ~exist(''TS_global'', ''var'') && exist(''TS'', ''var'') && ~isempty(TS)' newline ...
               '    TS_global = TS;' newline ...
               '    fprintf(''Created TS_global from TS\n'');' newline ...
               'end' newline ...
               '% Check which variables exist before saving' newline ...
               'varsToSave = {};' newline ...
               'varNames = {''net'', ''input'', ''target'', ''trainInp'', ''trainTarg'', ''trainOut'', ' ...
               '''valInp'', ''valTarg'', ''valOut'', ''testInp'', ''testTarg'', ''testOut'', ' ...
               '''tr'', ''PS_global'', ''TS_global''};' newline ...
               'for i = 1:length(varNames)' newline ...
               '    if exist(varNames{i}, ''var'')' newline ...
               '        varsToSave{end+1} = varNames{i};' newline ...
               '        fprintf(''Adding %s to save list\n'', varNames{i});' newline ...
               '    end' newline ...
               'end' newline ...
               'if ~isempty(varsToSave)' newline ...
               '    save(saveFilePath, varsToSave{:});' newline ...
               '    disp([''Saved '' num2str(length(varsToSave)) '' variables to '' saveFilePath]);' newline ...
               'else' newline ...
               '    disp(''Warning: No variables found to save!'');' newline ...
               'end'];
    
    modifiedContent = strrep(modifiedContent, 'save("Results_trained.mat");', saveCmd);
    
    % Replace the zip function call with updated paths
    zipFilePath = fullfile(trainingDir, 'Result_needed.zip');
    zipFilePath = strrep(zipFilePath, '\', '/');
    
    modifiedContent = strrep(modifiedContent, 'zip(''Result_needed.zip'', {''Results_trained.mat'',''Figures'', ''bpDNN4PyroProd.m''});', ...
        ['zip(''' zipFilePath ''', {''' saveFilePath ''', ''' figDirPath ''', ''' strrep(originalScript, '\', '/') '''});']);
    
    % Write the modified script to a temporary file
    fid = fopen(tempScript, 'w');
    if fid == -1
        error('Could not create temporary file: %s', tempScript);
    end
    fwrite(fid, modifiedContent);
    fclose(fid);
    
    % Store the temp script name in a local variable that we'll use immediately
    tempScriptName = 'bpDNN4PyroProd_temp';
    
    % Check and delete existing temporary files if already present
    tempGlobalsFile = fullfile(modelFilesDir, 'temp_globals.mat');
    if exist(tempGlobalsFile, 'file')
        delete(tempGlobalsFile);
        disp('Removed existing temporary globals file');
    end
    
    % Run the modified script
    run(tempScriptName);
    
    % Delete the temporary script after running
    if exist(tempScript, 'file')
        delete(tempScript);
        disp('Temporary script deleted successfully');
    end
    
    % Load global variables if saved separately
    globalVarsFile = fullfile(modelFilesDir, 'GlobalVars.mat');
    if exist(globalVarsFile, 'file')
        globalVarsData = load(globalVarsFile);
        if isfield(globalVarsData, 'PS_global') && isfield(globalVarsData, 'TS_global')
            assignin('base', 'PS_global', globalVarsData.PS_global);
            assignin('base', 'TS_global', globalVarsData.TS_global);
            disp('Global variables loaded from file');
        end
        delete(globalVarsFile);
    end
catch ME
    % Clean up in case of error
    if exist(tempScript, 'file')
        delete(tempScript);
    end
    if exist('GlobalVars.mat', 'file')
        delete('GlobalVars.mat');
    end
    cd(originalDir); % Make sure we return to original directory
    rethrow(ME);
end

% Return to original directory
cd(originalDir);

% Load the trained model data with better error checking
trainedDataFile = fullfile(trainingDir, 'Results_trained.mat');
trainedDataFile = strrep(trainedDataFile, '\', '/'); % Use forward slashes for consistency
if exist(trainedDataFile, 'file')
    try
        % Load with specific variable names to ensure they're all available
        trainVars = load(trainedDataFile);
        
        % Check for required variables and transfer to workspace
        requiredVars = {'net', 'input', 'target'};
        missingVars = setdiff(requiredVars, fieldnames(trainVars));
        
        if ~isempty(missingVars)
            disp(['Missing required variables in trained model data: ' strjoin(missingVars, ', ')]);
        end
        
        % Transfer variables to workspace
        fieldNames = fieldnames(trainVars);
        for i = 1:length(fieldNames)
            fieldName = fieldNames{i};
            assignin('base', fieldName, trainVars.(fieldName));
        end
        
        % Special handling for global variables
        global PS TS;
        if isfield(trainVars, 'PS_global') && isfield(trainVars, 'TS_global')
            PS = trainVars.PS_global;
            TS = trainVars.TS_global;
            disp('Global preprocessing variables set from trained data');
        elseif isfield(trainVars, 'data')
            if isfield(trainVars.data, 'PS') && isfield(trainVars.data, 'TS')
                PS = trainVars.data.PS;
                TS = trainVars.data.TS;
                disp('Global preprocessing variables set from data structure');
            end
        else
            disp('Could not set global preprocessing variables from trained data');
        end
        
        disp('Trained model data loaded successfully.');
    catch ME
        disp(['Error loading trained model data: ' ME.message]);
    end
else
    error('Cannot find trained model data at: %s', trainedDataFile);
end

disp('Model training complete with reduced epochs (60). Results saved in:');
disp(trainingDir);

%% Step 2: Perform SHAP analysis
disp('Starting SHAP analysis...');
disp(['SHAP results will be saved in: ' shapDir]);

% Ensure all required variables exist for SHAP analysis
if ~exist('net', 'var') || ~exist('input', 'var') || ~exist('target', 'var')
    disp('Warning: Missing required variables for SHAP analysis. Will attempt to load them from saved file.');
end

% Export key variables to base workspace
shapDir_var = shapDir;
modelFilesDir_var = modelFilesDir;
trainingDir_var = trainingDir;

% Check for parallel computing capabilities
try
    poolobj = gcp('nocreate');
    if isempty(poolobj)
        parpool('local');
        disp('Created parallel pool for SHAP computation');
    else
        disp(['Using existing parallel pool with ' num2str(poolobj.NumWorkers) ' workers']);
    end
catch ME
    disp(['Parallel Computing Toolbox not available: ' ME.message]);
end

% Save current directory
currDir = pwd;

% Change to script directory
cd(scriptDir);

% Create directory for SHAP data if it doesn't exist
shapDataDir = fullfile(shapDir, 'Data');
if ~exist(shapDataDir, 'dir')
    mkdir(shapDataDir);
end

% Create Figure directory for SHAP results if needed
shapFigDir = fullfile(shapDir, 'Figures');
if ~exist(shapFigDir, 'dir')
    mkdir(shapFigDir);
end

% Save globals to a mat file for the nested scripts to use
global PS TS;
tempGlobalsFile = fullfile(scriptDir, 'temp_globals.mat');
tempGlobalsFile = strrep(tempGlobalsFile, '\', '/'); % Use forward slashes for consistency

try
    if exist('PS', 'var') && exist('TS', 'var') && ~isempty(PS) && ~isempty(TS)
        % Ensure PS_global and TS_global exist
        PS_global = PS;
        TS_global = TS;
        save(tempGlobalsFile, 'PS', 'TS', 'PS_global', 'TS_global');
        disp('Global variables PS and TS saved to temp_globals.mat with PS_global and TS_global');
    else
        % Try to load global variables from training data
        try
            trainVars = load(trainedDataFile);
            if isfield(trainVars, 'PS_global') && isfield(trainVars, 'TS_global')
                PS = trainVars.PS_global;
                TS = trainVars.TS_global;
                PS_global = PS;
                TS_global = TS;
                save(tempGlobalsFile, 'PS', 'TS', 'PS_global', 'TS_global');
                disp('Global variables loaded from training data and saved to temp_globals.mat');
            end
        catch ME
            disp(['Could not retrieve global variables for temp file: ' ME.message]);
        end
    end
    
    % Create an embedded script with all necessary variables
    analyze_script = [
        'shapDir = ''' strrep(shapDir_var, '\', '/') ''';' newline ...
        'modelFilesDir = ''' strrep(modelFilesDir_var, '\', '/') ''';' newline ...
        'trainingDir = ''' strrep(trainingDir_var, '\', '/') ''';' newline ...
        'global PS TS;' newline ...
        'if exist(''temp_globals.mat'', ''file'')' newline ...
        '    temp = load(''temp_globals.mat'');' newline ...
        '    if isfield(temp, ''PS'') && isfield(temp, ''TS'')' newline ...
        '        PS = temp.PS;' newline ...
        '        TS = temp.TS;' newline ...
        '        % Also load PS_global and TS_global if available' newline ...
        '        if isfield(temp, ''PS_global'') && isfield(temp, ''TS_global'')' newline ...
        '            PS_global = temp.PS_global;' newline ...
        '            TS_global = temp.TS_global;' newline ...
        '            assignin(''base'', ''PS_global'', PS_global);' newline ...
        '            assignin(''base'', ''TS_global'', TS_global);' newline ...
        '        end' newline ...
        '        fprintf(''Loaded global preprocessing variables from temp file\n'');' newline ...
        '    else' newline ...
        '        fprintf(''Temp file exists but does not contain PS and TS variables\n'');' newline ...
        '    end' newline ...
        'else' newline ...
        '    fprintf(''Warning: temp_globals.mat not found\n'');' newline ...
        'end' newline ...
        'try' newline ...
        '    % Check if input and net are available in workspace' newline ...
        '    if ~exist(''input'', ''var'') || ~exist(''target'', ''var'') || ~exist(''net'', ''var'')' newline ...
        '        % Try to load from the training directory' newline ...
        '        trainedData = load(fullfile(trainingDir, ''Results_trained.mat''));' newline ...
        '        if isfield(trainedData, ''input'')' newline ...
        '            input = trainedData.input;' newline ...
        '        elseif isfield(trainedData, ''X_all'')' newline ...
        '            input = trainedData.X_all'';' newline ...
        '        end' newline ...
        '        if isfield(trainedData, ''target'')' newline ...
        '            target = trainedData.target;' newline ...
        '        elseif isfield(trainedData, ''y_all'')' newline ...
        '            target = trainedData.y_all'';' newline ...
        '        end' newline ...
        '        if isfield(trainedData, ''net'')' newline ...
        '            net = trainedData.net;' newline ...
        '        end' newline ...
        '        % Try to recover global variables if missing' newline ...
        '        if (~exist(''PS'', ''var'') || isempty(PS) || ~exist(''TS'', ''var'') || isempty(TS))' newline ...
        '            if isfield(trainedData, ''PS_global'') && isfield(trainedData, ''TS_global'')' newline ...
        '                PS = trainedData.PS_global;' newline ...
        '                TS = trainedData.TS_global;' newline ...
        '                PS_global = PS;' newline ...
        '                TS_global = TS;' newline ...
        '                fprintf(''Global preprocessing variables set from trained data\n'');' newline ...
        '            elseif isfield(trainedData, ''PS'') && isfield(trainedData, ''TS'')' newline ...
        '                PS = trainedData.PS;' newline ...
        '                TS = trainedData.TS;' newline ...
        '                PS_global = PS;' newline ...
        '                TS_global = TS;' newline ...
        '                fprintf(''Global preprocessing variables set directly\n'');' newline ...
        '            elseif isfield(trainedData, ''data'')' newline ...
        '                if isfield(trainedData.data, ''PS'') && isfield(trainedData.data, ''TS'')' newline ...
        '                    PS = trainedData.data.PS;' newline ...
        '                    TS = trainedData.data.TS;' newline ...
        '                    PS_global = PS;' newline ...
        '                    TS_global = TS;' newline ...
        '                    fprintf(''Global preprocessing variables set from data structure\n'');' newline ...
        '                end' newline ...
        '            elseif isfield(net, ''userdata'') && isfield(net.userdata, ''preprocessFcn'')' newline ...
        '                % Try to extract preprocessing info from network userdata if available' newline ...
        '                fprintf(''Attempting to extract preprocessing info from network userdata\n'');' newline ...
        '                if isfield(net.userdata, ''PS'') && isfield(net.userdata, ''TS'')' newline ...
        '                    PS = net.userdata.PS;' newline ...
        '                    TS = net.userdata.TS;' newline ...
        '                    PS_global = PS;' newline ...
        '                    TS_global = TS;' newline ...
        '                    fprintf(''Global preprocessing variables set from network userdata\n'');' newline ...
        '                end' newline ...
        '            else' newline ...
        '                fprintf(''Warning: Could not set global preprocessing variables\n'');' newline ...
        '            end' newline ...
        '        end' newline ...
        '        fprintf(''Loaded variables from training directory\n'');' newline ...
        '    end' newline ...
        '    % Generate predictions before running SHAP calculation (fixes prediction warning)' newline ...
        '    if exist(''net'', ''var'') && exist(''input'', ''var'')' newline ...
        '        try' newline ...
        '            predictions = nnpredict(net, input);' newline ...
        '            if ~isempty(predictions) && all(size(predictions) > 0)' newline ...
        '                fprintf(''Predictions calculated successfully: %dx%d matrix\n'', size(predictions, 1), size(predictions, 2));' newline ...
        '                % Make it available in base workspace too' newline ...
        '                assignin(''base'', ''predictions'', predictions);' newline ...
        '            else' newline ...
        '                fprintf(''Warning: Predictions calculation returned empty results\n'');' newline ...
        '            end' newline ...
        '        catch ME' newline ...
        '            fprintf(''Warning: Error calculating predictions: %s\n'', ME.message);' newline ...
        '        end' newline ...
        '    end' newline ...
        '    % Make sure the Data directory exists' newline ...
        '    if ~exist(fullfile(shapDir, ''Data''), ''dir'')' newline ...
        '        mkdir(fullfile(shapDir, ''Data''));' newline ...
        '    end' newline ...
        '    % Run the SHAP calculation' newline ...
        '    calc_shap_values;' newline ...
        '    fprintf(''SHAP analysis complete\n'');' newline ...
        '    % Export SHAP data to Excel' newline ...
        '    if exist(''export_shap_to_excel'', ''file'')' newline ...
        '        export_shap_to_excel;' newline ...
        '        fprintf(''SHAP data exported to Excel\n'');' newline ...
        '    else' newline ...
        '        fprintf(''Skipping Excel export - function not found\n'');' newline ...
        '        % Try to run anyway in case it''s in the path but not a file' newline ...
        '        try' newline ...
        '            export_shap_to_excel;' newline ...
        '            fprintf(''SHAP data exported to Excel\n'');' newline ...
        '        catch ME' newline ...
        '            fprintf(''Error exporting SHAP data to Excel: %s\n'', ME.message);' newline ...
        '        end' newline ...
        '    end' newline ...
        'catch ME' newline ...
        '    fprintf(''Error during SHAP analysis:\n'');' newline ...
        '    disp(getReport(ME, ''extended''));' newline ...
        'end' newline ...
        'try' newline ...
        '    % Fix input dimensions before plotting if needed' newline ...
        '    % Load SHAP values if not in workspace' newline ...
        '    if ~exist(''shapValues'', ''var'')' newline ...
        '        shapFile = fullfile(shapDir, ''Data'', ''shap_results.mat'');' newline ...
        '        if exist(shapFile, ''file'')' newline ...
        '            loadedData = load(shapFile);' newline ...
        '            if isfield(loadedData, ''shapValues'')' newline ...
        '                shapValues = loadedData.shapValues;' newline ...
        '            end' newline ...
        '            if isfield(loadedData, ''input'') && ~exist(''input'', ''var'')' newline ...
        '                input = loadedData.input;' newline ...
        '            end' newline ...
        '        end' newline ...
        '    end' newline ...
        '    % Fix input dimensions if needed' newline ...
        '    if exist(''shapValues'', ''var'') && exist(''input'', ''var'')' newline ...
        '        % Get SHAP value dimensions' newline ...
        '        if ndims(shapValues) == 3' newline ...
        '            [numInstances, numFeatures, ~] = size(shapValues);' newline ...
        '        else' newline ...
        '            [numInstances, numFeatures] = size(shapValues);' newline ...
        '        end' newline ...
        '        % Check input dimensions' newline ...
        '        if size(input, 1) ~= numInstances || size(input, 2) ~= numFeatures' newline ...
        '            % Try to transpose if that would make dimensions match' newline ...
        '            if size(input, 1) == numFeatures && size(input, 2) == numInstances' newline ...
        '                fprintf(''Transposing input to match SHAP values dimensions\n'');' newline ...
        '                input = input'';' newline ...
        '                % Make it available to plotting scripts' newline ...
        '                assignin(''base'', ''input'', input);' newline ...
        '                % Update in results structure if it exists' newline ...
        '                if exist(''results'', ''var'') && isfield(results, ''input'')' newline ...
        '                    results.input = input;' newline ...
        '                    % Save updated results' newline ...
        '                    save(fullfile(shapDir, ''Data'', ''shap_results.mat''), ''-struct'', ''results'');' newline ...
        '                end' newline ...
        '            end' newline ...
        '        end' newline ...
        '    end' newline ...
        '    % Run the plotting script' newline ...
        '    plot_shap_results;' newline ...
        '    fprintf(''Standard SHAP plots complete\n'');' newline ...
        '    % Run the original SHAP summary plot script' newline ...
        '    if exist(''plot_shap_original_summary'', ''file'')' newline ...
        '        plot_shap_original_summary;' newline ...
        '        fprintf(''Original SHAP summary plot complete\n'');' newline ...
        '    else' newline ...
        '        fprintf(''Skipping original SHAP summary plot - function not found\n'');' newline ...
        '        % Try to run anyway in case it''s in the path but not a file' newline ...
        '        try' newline ...
        '            plot_shap_original_summary;' newline ...
        '            fprintf(''Original SHAP summary plot complete\n'');' newline ...
        '        catch ME' newline ...
        '            fprintf(''Error running original SHAP summary: %s\n'', ME.message);' newline ...
        '        end' newline ...
        '    end' newline ...
        '    % Plot SHAP summary is already handled by plot_shap_original_summary script' newline ...
        '    % Run the beeswarm plotting script' newline ...
        '    if exist(''plot_shap_beeswarm'', ''file'')' newline ...
        '        plot_shap_beeswarm;' newline ...
        '        fprintf(''Beeswarm SHAP plots complete\n'');' newline ...
        '    else' newline ...
        '        fprintf(''Skipping beeswarm SHAP plot - function not found\n'');' newline ...
        '    end' newline ...
        'catch ME' newline ...
        '    fprintf(''Error during plotting:\n'');' newline ...
        '    disp(getReport(ME, ''extended''));' newline ...
        'end' newline ...
        '% Fix colorbar style for all SHAP plots' newline ...
        'try' newline ...
        '    if exist(''fix_colorbar_style'', ''file'')' newline ...
        '        fprintf(''Fixing colorbar style for all SHAP plots...\n'');' newline ...
        '        fix_colorbar_style;' newline ...
        '        fprintf(''Colorbar style fixed successfully\n'');' newline ...
        '    else' newline ...
        '        fprintf(''Skipping colorbar style fix - function not found\n'');' newline ...
        '    end' newline ...
        'catch ME' newline ...
        '    fprintf(''Error fixing colorbar style: %s\n'', ME.message);' newline ...
        'end' newline ...
        'if exist(''temp_globals.mat'', ''file'')' newline ...
        '    delete(''temp_globals.mat'');' newline ...
        '    fprintf(''Deleted temporary globals file\n'');' newline ...
        'end' newline ...
    ];
    
    % Write temporary script with proper error handling
    temp_script_file = fullfile(scriptDir, 'temp_analysis.m');
    fid = fopen(temp_script_file, 'w');
    if fid == -1
        error('Could not create temporary analysis file: %s', temp_script_file);
    end
    fwrite(fid, analyze_script);
    fclose(fid);
    
    % Run the embedded script
    run('temp_analysis.m');
    
    % Clean up temp files with proper error checking
    if exist(tempGlobalsFile, 'file')
        try
            delete(tempGlobalsFile);
            disp('Temporary globals file deleted');
        catch
            % Ignore errors during cleanup
            disp('Note: Could not delete temporary globals file');
        end
    end
    
    % Check for temp script file and try to clean it up too
    if exist('temp_script_file', 'var') && exist(temp_script_file, 'file')
        try
            delete(temp_script_file);
            disp('Cleaned up temporary script file during error handling');
        catch
            % Ignore errors during cleanup
            disp('Note: Could not clean up temporary script file during error handling');
        end
    end
    
catch ME
    % Ensure cleanup in case of error
    cd(currDir); % Make sure we return to original directory
    
    % Try to clean up temporary files
    if exist(tempGlobalsFile, 'file')
        try
            delete(tempGlobalsFile);
            disp('Cleaned up temporary globals file during error handling');
        catch
            % Ignore errors during cleanup
            disp('Note: Could not clean up temporary globals file during error handling');
        end
    end
    
    % Check for temp script file and try to clean it up too
    if exist('temp_script_file', 'var') && exist(temp_script_file, 'file')
        try
            delete(temp_script_file);
            disp('Cleaned up temporary script file during error handling');
        catch
            % Ignore errors during cleanup
            disp('Note: Could not clean up temporary script file during error handling');
        end
    end
    
    % Display error and rethrow
    disp(['Error during SHAP analysis: ' ME.message]);
    rethrow(ME);
end

% Delete the temporary script with error checking
if exist(temp_script_file, 'file')
    try
        delete(temp_script_file);
        disp('Temporary analysis script deleted successfully');
    catch ME
        disp(['Could not delete temporary analysis script: ' ME.message]);
    end
end

% Return to original directory
cd(currDir);

% Check if analysis produced results
resultsFile = fullfile(shapDir, 'Data', 'shap_results.mat');
resultsFile = strrep(resultsFile, '\', '/'); % Use forward slashes for consistency
if exist(resultsFile, 'file')
    disp('SHAP analysis results successfully generated.');
else
    disp('Warning: SHAP analysis did not produce any results file. Check for errors above.');
end

% Re-enable warnings
warning('on', 'MATLAB:nchoosek:LargeCoefficient');
warning('on', 'parallel:pctexample:parallelize');
warning('on', 'MATLAB:rmpath:DirNotFound');
warning('on', 'MATLAB:MKDIR:DirectoryExists');
warning('on', 'MATLAB:string:functionsToBeRemoved');

disp('Analysis complete! Results saved in:');
disp(resultsDir); 