function options = getGAOptions(optimizationType, numParams)
% getGAOptions  Centralized GA options with performanceConfig support
%
% options = getGAOptions('single_model'|'multi_model', numParams)

cfg = performanceConfig();

% Only enable parallel GA evaluation if a pool is already active.
% This prevents ga() from auto-creating a parpool (which hangs on HPC
% compute nodes when no pool can be started).
useParFlag = ~isempty(gcp('nocreate'));

switch optimizationType
  case 'single_model'
    if isfield(cfg, 'gaSingle')
      ps = cfg.gaSingle.populationSize;
      mg = cfg.gaSingle.maxGenerations;
      ec = cfg.gaSingle.eliteCount;
      cf = cfg.gaSingle.crossoverFraction;
      ft = cfg.gaSingle.functionTolerance;
    else
      ps = max(20, numParams * 6);
      mg = 10;
      ec = 3;
      cf = 0.8;
      ft = 1e-4;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  case 'multi_model'
    if isfield(cfg, 'gaMulti')
      ps = cfg.gaMulti.populationSize;
      mg = cfg.gaMulti.maxGenerations;
      ec = cfg.gaMulti.eliteCount;
      cf = cfg.gaMulti.crossoverFraction;
      ft = cfg.gaMulti.functionTolerance;
    else
      ps = 60;
      mg = 15;
      ec = 6;
      cf = 0.85;
      ft = 1e-5;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  case 'coarse'  % Stage 1: Quick screening with low-precision GA
    if isfield(cfg, 'twoStageGA') && isfield(cfg.twoStageGA, 'coarse')
      ps = cfg.twoStageGA.coarse.populationSize;
      mg = cfg.twoStageGA.coarse.maxGenerations;
      ec = cfg.twoStageGA.coarse.eliteCount;
      cf = cfg.twoStageGA.coarse.crossoverFraction;
      ft = cfg.twoStageGA.coarse.functionTolerance;
    else
      ps = 15; mg = 5; ec = 2; cf = 0.8; ft = 1e-4;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  case 'fine'  % Stage 2: Precise optimization with high-precision GA
    if isfield(cfg, 'twoStageGA') && isfield(cfg.twoStageGA, 'fine')
      ps = cfg.twoStageGA.fine.populationSize;
      mg = cfg.twoStageGA.fine.maxGenerations;
      ec = cfg.twoStageGA.fine.eliteCount;
      cf = cfg.twoStageGA.fine.crossoverFraction;
      ft = cfg.twoStageGA.fine.functionTolerance;
    else
      ps = 60; mg = 25; ec = 6; cf = 0.85; ft = 1e-6;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  case 'multi_coarse'  % Multi-mechanism Stage 1: Quick screening
    if isfield(cfg, 'twoStageGA') && isfield(cfg.twoStageGA, 'multiCoarse')
      ps = cfg.twoStageGA.multiCoarse.populationSize;
      mg = cfg.twoStageGA.multiCoarse.maxGenerations;
      ec = cfg.twoStageGA.multiCoarse.eliteCount;
      cf = cfg.twoStageGA.multiCoarse.crossoverFraction;
      ft = cfg.twoStageGA.multiCoarse.functionTolerance;
    else
      ps = 20; mg = 8; ec = 3; cf = 0.8; ft = 1e-4;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  case 'multi_fine'  % Multi-mechanism Stage 2: Precise optimization
    if isfield(cfg, 'twoStageGA') && isfield(cfg.twoStageGA, 'multiFine')
      ps = cfg.twoStageGA.multiFine.populationSize;
      mg = cfg.twoStageGA.multiFine.maxGenerations;
      ec = cfg.twoStageGA.multiFine.eliteCount;
      cf = cfg.twoStageGA.multiFine.crossoverFraction;
      ft = cfg.twoStageGA.multiFine.functionTolerance;
    else
      ps = 80; mg = 30; ec = 10; cf = 0.85; ft = 1e-6;
    end
    options = optimoptions('ga', ...
      'PopulationSize', ps, ...
      'MaxGenerations', mg, ...
      'EliteCount', ec, ...
      'CrossoverFraction', cf, ...
      'MutationFcn', @mutationadaptfeasible, ...
      'CrossoverFcn', @crossoverscattered, ...
      'SelectionFcn', @selectiontournament, ...
      'FunctionTolerance', ft, ...
      'Display', 'off', ...
      'UseParallel', useParFlag);

  otherwise
    error('Unknown optimization type: %s', optimizationType);
end
end
